$ErrorActionPreference = 'Stop'
[Console]::OutputEncoding = [Text.UTF8Encoding]::new($false)

$rawInput = [Console]::In.ReadToEnd()
if ([string]::IsNullOrWhiteSpace($rawInput)) {
  exit 0
}

$hookInput = $rawInput | ConvertFrom-Json
$filePath = [string]$hookInput.tool_input.file_path
if ([string]::IsNullOrWhiteSpace($filePath)) {
  exit 0
}

$projectRoot = [IO.Path]::GetFullPath($env:CLAUDE_PROJECT_DIR)
$resolvedPath = if ([IO.Path]::IsPathRooted($filePath)) {
  [IO.Path]::GetFullPath($filePath)
}
else {
  [IO.Path]::GetFullPath((Join-Path $projectRoot $filePath))
}

$relativePath = if ($resolvedPath.StartsWith($projectRoot, [StringComparison]::OrdinalIgnoreCase)) {
  $resolvedPath.Substring($projectRoot.Length).TrimStart('\', '/')
}
else {
  $resolvedPath
}

$fileName = [IO.Path]::GetFileName($resolvedPath)
$blockedReason = $null

if ($relativePath -match '(^|[\\/])\.git([\\/]|$)') {
  $blockedReason = 'Direct edits inside .git are prohibited.'
}
elseif ($fileName -eq '.env' -or $fileName -match '^\.env\..+$' -and $fileName -ne '.env.example') {
  $blockedReason = 'Direct edits to secret environment files are prohibited. Edit .env.example instead.'
}
elseif ($fileName -in @('pnpm-lock.yaml', 'package-lock.json', 'yarn.lock')) {
  $blockedReason = 'Lockfiles must be generated by the package manager, not edited directly.'
}

if ($blockedReason) {
  [ordered]@{
    hookSpecificOutput = [ordered]@{
      hookEventName = 'PreToolUse'
      permissionDecision = 'deny'
      permissionDecisionReason = "$blockedReason Target: $relativePath"
    }
  } | ConvertTo-Json -Depth 6 -Compress
}
